In [1]:
import numpy as np
import pandas as pd
from functions_for_simulation import *

In [2]:
Xs = Xs_generator(rowNum=200, colNum=400)
Xs

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x390,x391,x392,x393,x394,x395,x396,x397,x398,x399
0,1.167347,0.151666,-0.918396,-0.271479,1.211077,1.491461,0.586511,0.305644,1.733787,-1.615008,...,-1.609558,0.136298,0.904950,-1.012944,0.991415,-0.542004,0.669378,-0.120225,-0.654255,1.117257
1,-0.212072,-0.849130,-0.068623,0.484677,0.234738,0.872109,0.530374,-1.449495,0.533661,0.404094,...,1.114924,0.053877,-1.171545,0.443753,0.722060,0.694658,1.829050,-1.425014,0.782566,0.093550
2,1.134042,0.843421,-0.892205,1.044864,-1.725164,0.500002,-1.562384,1.702804,-0.787767,-1.160256,...,1.039421,-0.041501,0.858493,-0.025357,0.276592,-1.292167,-0.483639,0.150203,0.987945,-0.337043
3,-2.197752,-1.020547,-0.203853,-0.079188,0.934012,-0.740985,-0.416488,0.697996,-0.722443,1.239855,...,0.062209,-1.194770,-0.220294,0.035377,-0.217929,-0.657675,1.581358,1.431298,-0.015084,1.202974
4,-1.602277,0.711193,-0.010856,-0.262134,-0.221836,1.848755,-0.640326,0.394441,-1.635973,-0.762532,...,-0.669459,-1.211598,1.403864,1.994921,-0.613449,1.620724,-2.112243,-1.443632,-1.068625,-0.234876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.235281,0.515178,0.847707,0.323375,-1.499254,0.216035,-0.685309,0.538955,0.678086,1.034604,...,-0.443937,0.390200,-1.040423,-0.731953,0.033940,-1.697830,0.954921,-0.421569,-1.705196,-0.651506
196,0.408074,-0.481093,1.649827,1.539635,-0.444280,-0.875557,-1.039821,2.663252,-0.494624,-0.450265,...,-0.641113,1.462206,-0.262572,2.182861,0.894136,-0.026988,0.004210,0.076537,1.362858,0.691242
197,-0.580009,-2.187804,0.612737,-0.896731,0.184042,-1.349820,1.194102,0.509588,-0.093788,0.549047,...,-0.421491,0.896970,-0.248002,-0.025368,-1.173697,1.222622,1.197326,-0.243986,0.200369,-0.229835
198,-1.433523,-0.530215,-0.222476,0.251552,-0.362237,0.535556,-0.215896,-0.221547,-0.671916,-0.855501,...,0.606787,-0.556844,0.521550,-0.841415,0.736119,-1.685163,-0.974054,-1.588282,-1.096303,-1.076647
199,-0.241158,0.976275,1.274388,-0.816723,1.575949,-1.214633,-1.054735,-1.144383,0.216076,1.423731,...,-0.411946,-0.206346,1.101320,-0.982388,-1.324389,-0.409528,-0.304653,1.840971,0.000931,0.013349

In [3]:
Ws = np.ones(200)
df = Ys_generator(Xs, Ws, 0.5)
Xs

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x390,x391,x392,x393,x394,x395,x396,x397,x398,x399
0,1.167347,0.151666,-0.918396,-0.271479,1.211077,1.491461,0.586511,0.305644,1.733787,-1.615008,...,-1.609558,0.136298,0.904950,-1.012944,0.991415,-0.542004,0.669378,-0.120225,-0.654255,1.117257
1,-0.212072,-0.849130,-0.068623,0.484677,0.234738,0.872109,0.530374,-1.449495,0.533661,0.404094,...,1.114924,0.053877,-1.171545,0.443753,0.722060,0.694658,1.829050,-1.425014,0.782566,0.093550
2,1.134042,0.843421,-0.892205,1.044864,-1.725164,0.500002,-1.562384,1.702804,-0.787767,-1.160256,...,1.039421,-0.041501,0.858493,-0.025357,0.276592,-1.292167,-0.483639,0.150203,0.987945,-0.337043
3,-2.197752,-1.020547,-0.203853,-0.079188,0.934012,-0.740985,-0.416488,0.697996,-0.722443,1.239855,...,0.062209,-1.194770,-0.220294,0.035377,-0.217929,-0.657675,1.581358,1.431298,-0.015084,1.202974
4,-1.602277,0.711193,-0.010856,-0.262134,-0.221836,1.848755,-0.640326,0.394441,-1.635973,-0.762532,...,-0.669459,-1.211598,1.403864,1.994921,-0.613449,1.620724,-2.112243,-1.443632,-1.068625,-0.234876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.235281,0.515178,0.847707,0.323375,-1.499254,0.216035,-0.685309,0.538955,0.678086,1.034604,...,-0.443937,0.390200,-1.040423,-0.731953,0.033940,-1.697830,0.954921,-0.421569,-1.705196,-0.651506
196,0.408074,-0.481093,1.649827,1.539635,-0.444280,-0.875557,-1.039821,2.663252,-0.494624,-0.450265,...,-0.641113,1.462206,-0.262572,2.182861,0.894136,-0.026988,0.004210,0.076537,1.362858,0.691242
197,-0.580009,-2.187804,0.612737,-0.896731,0.184042,-1.349820,1.194102,0.509588,-0.093788,0.549047,...,-0.421491,0.896970,-0.248002,-0.025368,-1.173697,1.222622,1.197326,-0.243986,0.200369,-0.229835
198,-1.433523,-0.530215,-0.222476,0.251552,-0.362237,0.535556,-0.215896,-0.221547,-0.671916,-0.855501,...,0.606787,-0.556844,0.521550,-0.841415,0.736119,-1.685163,-0.974054,-1.588282,-1.096303,-1.076647
199,-0.241158,0.976275,1.274388,-0.816723,1.575949,-1.214633,-1.054735,-1.144383,0.216076,1.423731,...,-0.411946,-0.206346,1.101320,-0.982388,-1.324389,-0.409528,-0.304653,1.840971,0.000931,0.013349

In [4]:
df_filtered = df[df.columns[df.columns.str.contains('x')]]
df_filtered.columns

Index(['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9',
       ...
       'x390', 'x391', 'x392', 'x393', 'x394', 'x395', 'x396', 'x397', 'x398',
       'x399'],
      dtype='object', length=400)

In [5]:
Mahalanobis_distance(Xs, Ws)
# cov_X = np.cov(Xs)
# n = len(Ws)
# pw = np.sum(Ws) / n
# print(Xs.shape)
# print(cov_X.shape)

ValueError: Dot product shape mismatch, (200, 400) vs (200,)

In [15]:
Xs.cov

<bound method DataFrame.cov of            x0        x1        x2        x3        x4        x5        x6  \
0   -1.111051 -0.335438 -0.196432 -3.136527  0.636103 -0.326304  0.955534
1    0.038884  0.392361 -0.325006 -1.038601 -1.915163 -0.124809 -1.837524
2   -0.725580  2.127997 -0.644305  0.236981 -0.791357 -1.665610  1.689445
3   -1.602517 -0.257299 -0.598473  0.963777  0.323543 -0.774948  0.178028
4   -0.285212  0.873529 -0.525048 -0.019266  0.080552 -1.043279  0.453261
..        ...       ...       ...       ...       ...       ...       ...
195 -0.818595 -1.564059 -2.379185 -0.456104  0.722963 -0.864689 -0.410997
196  0.633429 -0.891271  0.057079  0.679916  0.714482 -0.774728 -0.807027
197  1.196182 -0.361129  0.898956  0.217669  0.478898  0.415182 -1.405305
198 -0.308657 -0.968997  1.105288  0.892820  2.270104  0.518829  0.217762
199 -2.226072  1.308324 -1.312018  0.138309 -0.511881  1.282624 -0.568592

           x7        x8        x9  ...      x390      x391      x392  \
0    0.397205 -0.267382  0.505818  ... -2.666928 -0.906986 -0.620208
1   -1.841502 -0.916679  0.737922  ...  0.239840  0.568514 -0.261621
2   -1.164811 -0.267264 -0.121483  ... -0.525547  2.142401 -1.036811
3   -0.145289 -0.059864  0.478673  ... -1.466296 -1.187236  0.509645
4    0.352430  2.066313 -0.722252  ...  0.042646  0.555379 -2.049490
..        ...       ...       ...  ...       ...       ...       ...
195  1.698379  1.146532 -0.493220  ... -0.383264  0.241373 -0.086204
196 -0.500103 -0.675596  0.473446  ...  0.050683  2.676163 -0.908097
197  2.103088 -0.077496  2.189635  ...  0.238042  0.699072 -1.929686
198 -0.050143  1.173321 -0.165654  ... -0.125766  0.101174 -2.030843
199  0.820343  0.281190  0.583375  ... -0.494859  0.293193 -0.351343

         x393      x394      x395      x396      x397      x398      x399
0    0.480818  0.421372 -1.206999 -1.364214 -0.364709  0.921164  1.669950
1   -1.027060 -1.254381  0.939729 -0.703280 -2.027967 -1.615279  0.210872
2    0.554810  0.842857 -0.036082 -0.096153 -2.347575 -2.007488  1.827057
3    1.521865 -1.115682  0.536580  0.262788 -1.586373 -0.777496  1.806868
4    2.398632 -1.027845 -1.212137 -1.498677 -0.388760 -0.204052 -3.041527
..        ...       ...       ...       ...       ...       ...       ...
195 -0.144977 -0.307629  0.145388  0.646389 -0.004786 -0.441344 -0.108731
196  1.392336 -0.531594  0.146521 -0.308677 -0.086557 -0.566732 -0.136345
197  0.407207 -0.056556 -0.594527 -0.297788  2.020708 -0.941126  1.417565
198  1.343828  0.518824  0.905568 -0.010194  1.233481  1.079284 -0.780474
199 -0.895160 -0.615704 -0.466768  0.458541  0.354244 -0.212936  0.611729

[200 rows x 400 columns]>