In [35]:
import numpy as np
import pandas as pd

In [36]:
rowNum = 200 
colNum = 400 #colNum should be 4000
mus = np.zeros(colNum)
sigma = np.eye(colNum)*2

In [37]:
Xs = np.random.multivariate_normal(mus, sigma, rowNum)
strs = ['x'+ str(i) for i in range(colNum)]
df = pd.DataFrame(Xs, columns=strs)
df.head(10)

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x390,x391,x392,x393,x394,x395,x396,x397,x398,x399
0,0.904117,-1.778878,-2.307366,-0.787228,-2.155718,0.599740,0.644228,1.268242,0.328340,-0.401282,...,-1.485506,0.337512,1.521926,-0.351915,-0.423030,1.014314,0.515076,-0.341983,-1.914492,0.588861
1,-0.033392,-0.391311,-2.770012,-2.012109,-1.653911,-1.083570,1.039760,1.260625,2.808376,-0.077564,...,-1.560208,-0.302151,0.305459,-0.566615,0.637686,0.934227,-0.467728,0.597374,-0.950356,-0.184271
2,-1.880419,-0.976708,1.048966,0.817083,-1.537675,0.221751,-2.163067,2.579905,1.288704,-1.011548,...,0.247609,2.097529,-0.140129,1.847340,-1.401968,1.372724,-2.943218,-0.395387,-1.637698,-2.293640
3,0.284455,0.916886,3.057256,-0.179562,-0.731233,0.003677,0.386272,-0.051774,1.243645,-2.549767,...,-1.864486,-0.693464,0.722028,-0.222769,-1.021335,0.836260,2.368926,-0.736532,-0.713851,0.008626
4,0.629502,0.473383,-0.717255,0.851228,2.604068,0.894251,-0.482011,0.274581,0.468201,-1.283365,...,-0.838999,-0.640431,0.471862,-0.150227,-0.250462,-2.397867,0.617523,1.524746,-0.181041,0.422155
5,-0.485696,1.210571,-2.645725,-1.596708,-0.393899,-0.690428,1.996259,-3.746386,0.219314,-1.743591,...,-2.847999,1.640051,0.357075,-2.131455,-1.787423,2.042499,1.039410,0.322483,2.774000,-0.080122
6,-0.332328,0.555415,0.171511,-1.706276,-0.061210,-2.958354,-0.494562,0.119329,1.352368,0.797364,...,-0.598580,-0.186265,0.026757,-0.531558,-0.756713,-1.006856,1.566862,-0.094689,-0.553902,0.994085
7,1.118427,-1.052890,2.818298,-0.413792,-1.472606,0.471442,2.427566,-1.883976,-2.538043,0.331540,...,-1.416989,-0.153936,-1.093373,-2.683019,2.663615,-0.821898,-0.452567,0.405006,-1.058715,-0.888098
8,-0.964111,-1.081295,2.188556,1.699848,1.741831,-1.437504,0.793163,1.518902,-0.685245,1.056384,...,-0.098936,-0.338157,1.003605,1.015971,-1.163308,2.725159,1.932512,0.197463,-2.595262,1.449369
9,-0.987273,-0.976780,0.961502,0.552382,0.382953,0.091402,0.446893,-3.483149,2.411746,-0.451692,...,-2.127673,-0.549779,-0.726427,1.069249,2.961828,1.226628,5.055270,0.339073,0.158417,-2.832712

In [38]:
tau = 0.8

beta1 = [np.random.uniform(-1, 1) for i in range(colNum)]
beta_norm2 = np.linalg.norm(beta1)
desired_norm = 20
beta1 = beta1 / beta_norm2 * desired_norm

beta0 = np.random.uniform(-1, 1)
eps = np.random.normal(0, 1, rowNum)
Ys = beta0 + np.dot(df, beta1) + eps

df['y'] = Ys

df

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x391,x392,x393,x394,x395,x396,x397,x398,x399,y
0,0.904117,-1.778878,-2.307366,-0.787228,-2.155718,0.599740,0.644228,1.268242,0.328340,-0.401282,...,0.337512,1.521926,-0.351915,-0.423030,1.014314,0.515076,-0.341983,-1.914492,0.588861,-35.222114
1,-0.033392,-0.391311,-2.770012,-2.012109,-1.653911,-1.083570,1.039760,1.260625,2.808376,-0.077564,...,-0.302151,0.305459,-0.566615,0.637686,0.934227,-0.467728,0.597374,-0.950356,-0.184271,5.719039
2,-1.880419,-0.976708,1.048966,0.817083,-1.537675,0.221751,-2.163067,2.579905,1.288704,-1.011548,...,2.097529,-0.140129,1.847340,-1.401968,1.372724,-2.943218,-0.395387,-1.637698,-2.293640,23.069349
3,0.284455,0.916886,3.057256,-0.179562,-0.731233,0.003677,0.386272,-0.051774,1.243645,-2.549767,...,-0.693464,0.722028,-0.222769,-1.021335,0.836260,2.368926,-0.736532,-0.713851,0.008626,-12.795711
4,0.629502,0.473383,-0.717255,0.851228,2.604068,0.894251,-0.482011,0.274581,0.468201,-1.283365,...,-0.640431,0.471862,-0.150227,-0.250462,-2.397867,0.617523,1.524746,-0.181041,0.422155,-56.424051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-0.409301,1.234017,0.321025,-0.454360,0.848053,-0.167484,-2.083995,0.030572,-1.059606,-0.289476,...,-2.098453,-1.564316,-0.262130,0.879755,-0.642397,-0.196041,0.913631,1.230350,0.925992,34.767716
196,-1.308987,2.335869,2.197950,-1.142719,2.212501,-0.197261,-0.337187,0.840501,1.230357,2.674574,...,-0.604932,-0.846388,-0.234694,0.780603,0.495829,-0.682292,-2.211534,1.871691,0.346709,35.392075
197,0.037212,-2.840174,-0.884037,-1.709675,2.673574,2.039588,0.479319,0.483871,-1.571601,-2.373063,...,0.455313,-0.181492,1.300286,0.710615,0.306896,-0.085502,-0.080729,1.136992,0.804188,8.534170
198,-0.229515,0.819623,0.888114,-1.460517,-0.342659,-1.654417,1.234537,0.699329,-0.730547,0.155590,...,-0.829988,0.874085,0.338337,-1.589976,-0.734867,-1.958398,1.598754,-2.212589,1.938067,10.131139
199,-1.319300,0.080441,3.363033,0.292024,-2.564998,1.999273,1.031696,-0.795318,0.965741,0.669758,...,0.776978,-1.196770,-0.526365,1.287140,-0.077387,-0.385984,2.102595,2.044471,1.823425,-8.740921

In [43]:
data = pd.DataFrame([[1, 2],[3,4]], columns=['A', 'B'])
print(data)
print(np.dot(data, [1,1]))

   A  B
0  1  2
1  3  4
[3 7]